Docs updates
boxyhq/website pull request #159
Opened 2023-01-19 10:31 UTC by ukrocks007

- Setup link documentation
- Screenshots updated
- Audit logs admin portal page shifted
- Added retraced architectural diagram
- retraced self-host and deploy sections merged
- Removed auth0 environment variables

2023-01-19 16:38 UTC, devkiran requested changes
- I think there are some missing headings in the docs. Here is a screenshot of the same. Please take a look at it. ![doc-1](https://user-images.githubusercontent.com/4593041/213501052-92f7bb81-7636-4e51-93ba-40af1664261e.png)

- Can we use the Markdown syntax for the images? It will be easier to maintain and will be consistent with the rest of the docs. Docusaurus add zoom functionality to the images when we use the Markdown syntax. Not sure if we can do the same with the HTML syntax.

- It would better to use "Admin Portal" instead of "Admin UI" in the docs. (/docs/admin-portal/audit-logs). We are using "Admin Portal" other places as well.

2023-01-20 10:22 UTC, ukrocks007 commented
> * I think there are some missing headings in the docs. Here is a screenshot of the same. Please take a look at it. ![doc-1](https://user-images.githubusercontent.com/4593041/213501052-92f7bb81-7636-4e51-93ba-40af1664261e.png)
> * Can we use the Markdown syntax for the images? It will be easier to maintain and will be consistent with the rest of the docs. Docusaurus add zoom functionality to the images when we use the Markdown syntax. Not sure if we can do the same with the HTML syntax.
> * It would better to use "Admin Portal" instead of "Admin UI" in the docs. (/docs/admin-portal/audit-logs). We are using "Admin Portal" other places as well.

Fixed

2023-01-20 12:59 UTC, deepakprabhakara commented on docs/directory-sync/setup-link.md
> +---
This should go into Admin Portal section right?

2023-01-20 12:59 UTC, deepakprabhakara commented on docs/jackson/setup-link.md
> +---
This should go into Admin Portal section right?

2023-01-24 23:36 UTC, deepakprabhakara commented on docs/retraced/sbom.md
> +**Note:** This is supported for all versions >=0.3.8
>=v1.5.0

2023-01-24 23:48 UTC, deepakprabhakara approved these changes

2023-01-24 23:49 UTC, merged