Update the doc
boxyhq/website pull request #18
Opened 2022-02-02 13:50 UTC by devkiran

2022-02-02 13:53 UTC, deepakprabhakara requested changes

2022-02-02 13:53 UTC, deepakprabhakara commented on docs/jackson/deploy.md
> +  -e DB_ENCRYPTION_KEY="fwTul69Mf0nZDr+L1SG9gqwcOkyieybu" \
Let's not include any encryption keys since people tend to copy paste and forget about it

2022-02-02 14:46 UTC, devkiran commented
@deepakprabhakara Done

2022-02-10 02:00 UTC, deepakprabhakara approved these changes
Nice work @devkiran

2022-02-10 02:01 UTC, merged